project_id = "easy-waiter"

[api]
enabled = true
port = 55321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 55322
major_version = 17

[studio]
enabled = true
port = 55323

[storage]
enabled = true

[inbucket]
enabled = true
port = 55324

[analytics]
enabled = true
port = 55327

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
